### ISSUE TITLE
Could not create a new directory

### ISSUE THREAD

**Issue by xnvmx** [panictriggers/snapcatch#1]
Why might this not work for me? My device is rooted.
I present below the result of running the script:
![failed](https://user-images.githubusercontent.com/92065189/144833973-0e9ddaa0-7bd1-4a08-b7f5-44003511a4a1.png)

**Comment by showengineer** [comment]
As the error tells you, the filesystem is mounted as read-only. You need to be able to write to the filesystem for this to work.

**Comment by showengineer** [comment]
What app are you using to execute this script? Maybe we can find out why the filesystem is marked readonly

**Comment by xnvmx** [comment]
I don't want to root on my own phone, so I'm using an android emulator called LDPlayer.
I don't use any application, but I hold your file with the .sh extension longer and then the menu is displayed. I choose "Execute" from all the options.

**Comment by showengineer** [comment]
The video doesn't work but basically you need to mount your SD storage as write (and exec prefferably)

**Comment by showengineer** [comment]
I believe you can do that with `mount -o rw,remount /sdcard` but don't take my word for it (and be careful with that command)

**Comment by xnvmx** [comment]
> The video doesn't work but basically you need to mount your SD storage as write (and exec prefferably)

I did it. You were right. Storage was locked for writing.

**Comment by showengineer** [comment]
Great! Does it work now?

**Comment by xnvmx** [comment]
> I believe you can do that with `mount -o rw,remount /sdcard` but don't take my word for it (and be careful with that command)

I didn't do it with a command, but with the file manager. I just unchecked this padlock at the top and the folder with snaps was created after executing your script.
![Screenshot_20211206-150145](https://user-images.githubusercontent.com/92065189/144860933-83bbb726-1edd-41d0-81fc-12732c7f8571.png)

**Comment by xnvmx** [comment]
> Great! Does it work now?

Everything works great this way 🧡 I just need to move the folder to internal storage for example "pictures" or "download", otherwise these snaps won't show up in the default location. 
Is it possible in the next update of the script to be able to choose the save location?

**Comment by showengineer** [comment]
I'll put it on the list but good to hear it works
